# Generated by Django 2.2.6 on 2019-10-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtag',
            name='type',
            field=models.CharField(choices=[('PERSON', 'Person'), ('EMOTION', 'Emotion'), ('CONDITION', 'Mental Condition')], default='CUSTOM', max_length=80),
        ),
        migrations.AddConstraint(
            model_name='eventtag',
            constraint=models.UniqueConstraint(fields=('name', 'event'), name='unique tag per event'),
        ),
        migrations.AddConstraint(
            model_name='segmenttag',
            constraint=models.UniqueConstraint(fields=('name', 'segment'), name='unique tag per event'),
        ),
    ]
