# Generated by Django 2.2.6 on 2019-10-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_auto_20191008_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmenttag',
            name='type',
            field=models.CharField(choices=[('PERSON', 'Person'), ('EMOTION', 'Emotion'), ('CUSTOM', 'Custom'), ('STORY_ARC', 'Story Arc')], default='CUSTOM', max_length=80),
        ),
    ]
