export class constants {

  public static TYPE_TO_ICON={
    // Material icons
    'emotion':'sentiment_very_satisfied',
    'person':'person',
    'place':'place',
    'custom':'label_important'
  }

  public static BASE_EMOTION_COLOR = {
    'happy': 'gold',
    'disgusted': 'grey',
    'surprised': 'purple',
    'sad': 'lightskyblue',
    'angry': 'crimson',
    'bad': 'lightgreen',
    'fearful': 'goldenrod',
  }



  public static BOTTOM_LEVEL_EMOTIONS = {
    "startled": "surprised",
    "shocked": "surprised",
    "dismayed": "surprised",
    "confused": "surprised",
    "disillusioned": "surprised",
    "perplexed": "surprised",
    "amazed": "surprised",
    "astonished": "surprised",
    "awe": "surprised",
    "excited": "surprised",
    "eager": "surprised",
    "energetic": "surprised",
    "surprised":"surprised",
    "playful": "happy",
    "aroused": "happy",
    "cheeky": "happy",
    "content": "happy",
    "free": "happy",
    "joyful": "happy",
    "interested": "happy",
    "curious": "happy",
    "inquisitive": "happy",
    "proud": "happy",
    "successful": "happy",
    "confident": "happy",
    "accepted": "happy",
    "respected": "happy",
    "valued": "happy",
    "powerful": "happy",
    "courageous": "happy",
    "creative": "happy",
    "trusting": "happy",
    "sensitive": "happy",
    "intimate": "happy",
    "optimistic": "happy",
    "hopeful": "happy",
    "inspired": "happy",
    "happy":"happy",
    "lonely": "sad",
    "isolated": "sad",
    "abandoned": "sad",
    "vulnerable": "sad",
    "victimized": "sad",
    "fragile": "sad",
    "despair": "sad",
    "grief": "sad",
    "powerless": "sad",
    "guilty": "sad",
    "ashamed": "sad",
    "remorseful": "sad",
    "depressed": "sad",
    "inferior": "fearful",
    "empty": "sad",
    "hurt": "sad",
    "dissapointed": "sad",
    "embarrased": "sad",
    "sad":"sad",
    "disapproving": "disgusted",
    "judgmental": "disgusted",
    "embarrassed": "disgusted",
    "disappointed": "disgusted",
    "appalled": "disgusted",
    "revolted": "disgusted",
    "awful": "disgusted",
    "nauseated": "disgusted",
    "detestable": "disgusted",
    "repelled": "disgusted",
    "horrified": "disgusted",
    "hesitant": "disgusted",
    "disgusted":"disgusted",
    "let down": "angry",
    "betrayed": "angry",
    "resentful": "angry",
    "humiliated": "angry",
    "disrespected": "angry",
    "ridiculed": "angry",
    "bitter": "angry",
    "indignant": "angry",
    "violated": "angry",
    "mad": "angry",
    "furious": "angry",
    "jealous": "angry",
    "aggressive": "angry",
    "provoked": "angry",
    "hostile": "angry",
    "frustrated": "angry",
    "infuriated": "angry",
    "annoyed": "angry",
    "distant": "angry",
    "withdrawn": "angry",
    "numb": "angry",
    "critical": "angry",
    "skeptical": "angry",
    "dismissive": "angry",
    "angry":"angry",
    "scared": "fearful",
    "helpess": "fearful",
    "frightened": "fearful",
    "anxious": "fearful",
    "overwhelmed": "bad",
    "worried": "fearful",
    "insecure": "fearful",
    "inadequate": "fearful",
    "weak": "fearful",
    "worthless": "fearful",
    "insignificant": "fearful",
    "rejected": "fearful",
    "excluded": "fearful",
    "persecuted": "fearful",
    "threatened": "fearful",
    "nervous": "fearful",
    "exposed": "fearful",
    "fearful":"fearful",
    "bored": "bad",
    "indifferent": "bad",
    "apathetic": "bad",
    "busy": "bad",
    "pressured": "bad",
    "rushed": "bad",
    "stressed": "bad",
    "out of control": "bad",
    "tired": "bad",
    "sleepy": "bad",
    "unfocussed": "bad",
    "bad":"bad"
  }
}