TOP_LEVEL_EMOTIONS = \
{
  'accepted': ['respected', 'valued'],
  'aggressive': ['provoked', 'hostile'],
  'amazed': ['astonished', 'awe'],
  'angry': ['betrayed',
            'resentful',
            'let down',
            'disrespected',
            'ridiculed',
            'humiliated',
            'indignant',
            'violated',
            'bitter',
            'furious',
            'jealous',
            'mad',
            'provoked',
            'hostile',
            'aggressive',
            'infuriated',
            'annoyed',
            'frustrated',
            'withdrawn',
            'numb',
            'distant',
            'skeptical',
            'dismissive',
            'critical'],
  'anxious': ['overwhelmed', 'worried'],
  'awful': ['nauseated', 'detestable'],
  'bad': ['indifferent',
          'apathetic',
          'bored',
          'pressured',
          'rushed',
          'busy',
          'overwhelmed',
          'out of control',
          'stressed',
          'sleepy',
          'unfocussed',
          'tired'],
  'bitter': ['indignant', 'violated'],
  'bored': ['indifferent', 'apathetic'],
  'busy': ['pressured', 'rushed'],
  'confused': ['disillusioned', 'perplexed'],
  'content': ['free', 'joyful'],
  'critical': ['skeptical', 'dismissive'],
  'depressed': ['inferior', 'empty'],
  'despair': ['grief', 'powerless'],
  'disappointed': ['appalled', 'revolted'],
  'disapproving': ['judgmental', 'embarrassed'],
  'disgusted': ['judgmental',
                'embarrassed',
                'disapproving',
                'appalled',
                'revolted',
                'disappointed',
                'nauseated',
                'detestable',
                'awful',
                'horrified',
                'hesitant',
                'repelled'],
  'distant': ['withdrawn', 'numb'],
  'excited': ['eager', 'energetic'],
  'fearful': ['helpess',
              'frightened',
              'scared',
              'overwhelmed',
              'worried',
              'anxious',
              'inadequate',
              'inferior',
              'insecure',
              'worthless',
              'insignificant',
              'weak',
              'excluded',
              'persecuted',
              'rejected',
              'nervous',
              'exposed',
              'threatened'],
  'frustrated': ['infuriated', 'annoyed'],
  'guilty': ['ashamed', 'remorseful'],
  'happy': ['aroused',
            'cheeky',
            'playful',
            'free',
            'joyful',
            'content',
            'curious',
            'inquisitive',
            'interested',
            'successful',
            'confident',
            'proud',
            'respected',
            'valued',
            'accepted',
            'courageous',
            'creative',
            'powerful',
            'sensitive',
            'intimate',
            'trusting',
            'hopeful',
            'inspired',
            'optimistic'],
  'humiliated': ['disrespected', 'ridiculed'],
  'hurt': ['dissapointed', 'embarrased'],
  'insecure': ['inadequate', 'inferior'],
  'interested': ['curious', 'inquisitive'],
  'let down': ['betrayed', 'resentful'],
  'lonely': ['isolated', 'abandoned'],
  'mad': ['furious', 'jealous'],
  'optimistic': ['hopeful', 'inspired'],
  'playful': ['aroused', 'cheeky'],
  'powerful': ['courageous', 'creative'],
  'proud': ['successful', 'confident'],
  'rejected': ['excluded', 'persecuted'],
  'repelled': ['horrified', 'hesitant'],
  'sad': ['isolated',
          'abandoned',
          'lonely',
          'victimized',
          'fragile',
          'vulnerable',
          'grief',
          'powerless',
          'despair',
          'ashamed',
          'remorseful',
          'guilty',
          'inferior',
          'empty',
          'depressed',
          'dissapointed',
          'embarrased',
          'hurt'],
  'scared': ['helpess', 'frightened'],
  'startled': ['shocked', 'dismayed'],
  'stressed': ['overwhelmed', 'out of control'],
  'surprised': ['shocked',
                'dismayed',
                'startled',
                'disillusioned',
                'perplexed',
                'confused',
                'astonished',
                'awe',
                'amazed',
                'eager',
                'energetic',
                'excited'],
  'threatened': ['nervous', 'exposed'],
  'tired': ['sleepy', 'unfocussed'],
  'trusting': ['sensitive', 'intimate'],
  'vulnerable': ['victimized', 'fragile'],
  'weak': ['worthless', 'insignificant']
}



BOTTOM_LEVEL_EMOTIONS = {
    "startled": "surprised",
    "shocked": "surprised",
    "dismayed": "surprised",
    "confused": "surprised",
    "disillusioned": "surprised",
    "perplexed": "surprised",
    "amazed": "surprised",
    "astonished": "surprised",
    "awe": "surprised",
    "excited": "surprised",
    "eager": "surprised",
    "energetic": "surprised",
    "surprised":"surprised",
    "playful": "happy",
    "aroused": "happy",
    "cheeky": "happy",
    "content": "happy",
    "free": "happy",
    "joyful": "happy",
    "interested": "happy",
    "curious": "happy",
    "inquisitive": "happy",
    "proud": "happy",
    "successful": "happy",
    "confident": "happy",
    "accepted": "happy",
    "respected": "happy",
    "valued": "happy",
    "powerful": "happy",
    "courageous": "happy",
    "creative": "happy",
    "trusting": "happy",
    "sensitive": "happy",
    "intimate": "happy",
    "optimistic": "happy",
    "hopeful": "happy",
    "inspired": "happy",
    "happy":"happy",
    "lonely": "sad",
    "isolated": "sad",
    "abandoned": "sad",
    "vulnerable": "sad",
    "victimized": "sad",
    "fragile": "sad",
    "despair": "sad",
    "grief": "sad",
    "powerless": "sad",
    "guilty": "sad",
    "ashamed": "sad",
    "remorseful": "sad",
    "depressed": "sad",
    "inferior": "fearful",
    "empty": "sad",
    "hurt": "sad",
    "dissapointed": "sad",
    "embarrased": "sad",
    "sad":"sad",
    "disapproving": "disgusted",
    "judgmental": "disgusted",
    "embarrassed": "disgusted",
    "disappointed": "disgusted",
    "appalled": "disgusted",
    "revolted": "disgusted",
    "awful": "disgusted",
    "nauseated": "disgusted",
    "detestable": "disgusted",
    "repelled": "disgusted",
    "horrified": "disgusted",
    "hesitant": "disgusted",
    "disgusted":"disgusted",
    "let down": "angry",
    "betrayed": "angry",
    "resentful": "angry",
    "humiliated": "angry",
    "disrespected": "angry",
    "ridiculed": "angry",
    "bitter": "angry",
    "indignant": "angry",
    "violated": "angry",
    "mad": "angry",
    "furious": "angry",
    "jealous": "angry",
    "aggressive": "angry",
    "provoked": "angry",
    "hostile": "angry",
    "frustrated": "angry",
    "infuriated": "angry",
    "annoyed": "angry",
    "distant": "angry",
    "withdrawn": "angry",
    "numb": "angry",
    "critical": "angry",
    "skeptical": "angry",
    "dismissive": "angry",
    "angry":"angry",
    "scared": "fearful",
    "helpess": "fearful",
    "frightened": "fearful",
    "anxious": "fearful",
    "overwhelmed": "bad",
    "worried": "fearful",
    "insecure": "fearful",
    "inadequate": "fearful",
    "weak": "fearful",
    "worthless": "fearful",
    "insignificant": "fearful",
    "rejected": "fearful",
    "excluded": "fearful",
    "persecuted": "fearful",
    "threatened": "fearful",
    "nervous": "fearful",
    "exposed": "fearful",
    "fearful":"fearful",
    "bored": "bad",
    "indifferent": "bad",
    "apathetic": "bad",
    "busy": "bad",
    "pressured": "bad",
    "rushed": "bad",
    "stressed": "bad",
    "out of control": "bad",
    "tired": "bad",
    "sleepy": "bad",
    "unfocussed": "bad",
    "bad":"bad"
  }