# Generated by Django 2.2.6 on 2019-10-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PERSON', 'Person'), ('CUSTOM', 'Custom'), ('STORY_ARC', 'Story Arc')], default='CUSTOM', max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='segment.Segment')),
            ],
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EMOTION', 'Emotion'), ('CONDITION', 'Mental Condition')], default='CUSTOM', max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='segment.Event')),
            ],
        ),
    ]
