# Generated by Django 2.2.6 on 2019-10-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='type',
            field=models.CharField(choices=[('EVENT', 'Event'), ('THOUGHT', 'Thought'), ('INFERENCE', 'Inference'), ('DREAM', 'Dream'), ('CUSTOM', 'Custom')], default='EVENT', max_length=150),
        ),
    ]
